Optimise time taken in "preparing to export" state.
AssetRipper/AssetRipper pull request #627
Opened 2022-12-01 02:05 UTC by SamboyCoding

On my test game these optimizations took the preparing time from several hours to less than 30 seconds.

2022-12-02 18:16 UTC, ds5678 requested changes
Looking good. I've left some comments with changes to be done. 

As I said in Discord, I'm still worried about [this line](https://github.com/AssetRipper/AssetRipper/blob/5852b99aeb34c66259229236c341448692e2e4cf/AssetRipper.Library/Processors/Textures/SpriteProcessor.cs#L94), which will have to be investigated. @trouger can you shed some light on why the texture is being reassigned? The code was pulled from the `YamlSpriteExporter` you contributed in #488.

In addition, I have not yet verified with WinMerge that everything is being exported the same.

2022-12-02 18:16 UTC, ds5678 commented on AssetRipper.Core/Project/Collections/AssetsExportCollection.cs
>  		protected readonly Dictionary<AssetInfo, long> m_exportIDs = new();
This can be made private and changed to `Dictionary<IUnityObjectBase, long>`. `m_assets` can be removed.

2022-12-02 18:16 UTC, ds5678 commented on AssetRipper.Library/Exporters/Textures/TextureExportCollection.cs
> +		// }
Remove all of this.

2022-12-02 18:16 UTC, ds5678 commented on AssetRipper.Library/Exporters/Textures/TextureExportCollection.cs
> +		// private readonly Dictionary<ISprite, ISpriteAtlas?> m_sprites = new();
Remove

2022-12-02 18:16 UTC, ds5678 commented on AssetRipper.Library/Exporters/Textures/YamlSpriteExporter.cs
> +			// sprite.RD_C213.TextureRectOffset.Y = sprite.RD_C213.TextureRect.Y - rect.Y;
Remove all of this

2022-12-02 18:16 UTC, ds5678 commented on AssetRipper.Library/Exporters/Textures/TextureExportCollection.cs
> +					if (sprite.RD_C213.Texture.IsAsset(sprite.Collection, texture))
This should always be true. Please convert it to a `Debug.Assert` call.

2022-12-02 23:31 UTC, SamboyCoding commented
Whoops, sorry about the commenting out, bad habits from another codebase 🙃. Addressing this now

2022-12-03 00:05 UTC, ds5678 requested changes
Your changes look good. Just a small nitpicky request. Great work on all of this!

I'll verify consistency with WinMerge soon. Also, @trouger will hopefully chime in on my texture reassignment concerns.

Once this is addressed, we should be good for merge and then a 3.0 release shortly after.

2022-12-03 16:40 UTC, ds5678 commented
> I'll verify consistency with WinMerge soon.

`SpriteExportMode.Yaml` is the default setting. With it, I have verified that output is consistent.

However, texture meta files differ significantly when using other `SpriteExportMode`s. I think this may be unavoidable. Since the Yaml mode is supposedly superior, I may hide this setting from users until further investigation can be done.

2022-12-03 16:42 UTC, merged