Cache all the animator's paths CRC before resolving them
AssetRipper/AssetRipper pull request #973
Opened 2023-08-07 23:21 UTC by aldelaro5

Supersedes parts of #856 

This pr changes the way we approach animation clips's paths resolution. It includes a relatively large refactor that removes TOSBuilder to move its logic into PathChecksumCache (since it seemed underutilised and seemed to do what I wanted it to do better than TOSBuilder which is now less well named).

Previously, we tried to recover the path from the CRC with the assumption that a given clip MUST have an animator or animations with a bound controller containing the clip. While this might be true and it could allow easier recovery, tests and reversing of unity shows that cannot be guaranteed due to the runtime features of animation controllers. What unity does at runtime is whenever the controller is set to the animator and enabled, it will gather all possible path from its GO down the hierarchy to build a CRC cache and use that cache to resolve the bindings to the transforms.

This gives AssetRipper 3 potential scenarios to handle instead of 1:
1. The clip is contained in a controller bound to an animator (what AssetRipper currently assumes)
2. The clip is contained in a controller that has no animator bound to it, but an animator exists at the GO meant to receive the controller at runtime (currently fallsback to `path_`, but recoverable)
3. The clip is not contained in a controller or it is, but no animator exists at the GO meant to receive it (currently fallsback to `path_`, this is irrecoverable since everything happens at runtime)

Scenario 2 is where most of the reported issues about `path_` are and they could be recovered. However, it turns out there is something better than nothing for scenario 3: we can now reverse a CRC string which is most likely incorrect, but technically can work better than nothing.

The way this pr achieves this is by turning around what we do: instead of building the crc cache for each clip and rely on it, this pr builds a global crc cache before processing any clips and from there, every clips uses that cache. This happens to cover scenario 1 implicitly because if it happens, it implies an animator must be present there.

The complexity is O(N) because building the cache is O(N), but since we use a dictionary, looking up a crc is O(1) afterwards. This differs from #856 because that pr was still using the same structure TOSBuilder had which effectively made it per clip per animator or O(N)^2. Finally, if this cannot be found in the cache, we falback to a reversed CRC instead.

Fixes
#853 (another part of it not mentioned will be fixed in another pr)
parts of #954 (the rest is fixed by another pr)

cc: @o5zereth

2023-08-07 23:23 UTC, o5zereth commented
Nice! :D

2023-08-07 23:42 UTC, ds5678 requested changes
Just a start so you can continue working.

2023-08-07 23:42 UTC, ds5678 commented on Source/AssetRipper.Processing/AnimationClips/PathChecksumCache.cs
> +	public void BuildPathsCache(AnimationCache cache)
Use `GameBundle` as the parameter and delete the `AnimationCache` class.

2023-08-08 00:04 UTC, ds5678 requested changes
Looking great so far.

2023-08-08 00:04 UTC, ds5678 commented on Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs
> +				return Crc32Algorithm.ReverseAscii(hash, UnknownPathPrefix);
Can we do this instead? 
```cs
Crc32Algorithm.ReverseAscii(hash, $"{UnknownPathPrefix}0x{hash:X}_")
```
That would embed the original hash in the output.

2023-08-08 00:47 UTC, ds5678 approved these changes

2023-08-08 00:48 UTC, merged